config/routes.rb
Rails.application.routes.draw do
  root to: 'concerts#index'
  get '/concerts/authorize', to: 'concerts#connect'
  get '/concerts/:id/like/:track_id', to: 'concerts#show'
  get '/concerts/:id/comments/:comment', to: 'concerts#show'
  resources :concerts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  include ConcertsHelper
  helper_method :current_user

  def current_user
  	@current_user ||= session[:user] if session[:user]
  	if @current_user
  		@current_user
  	else
  		'Guest'
  	end
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_filter :get_params
  before_filter :soundcloud_connect
  
  def index
    @doc = Nokogiri::HTML(open('http://www.cheapthrills.ca/news.html'), nil, 'ISO-8859-1')
    @doc.encoding = 'UTF-8'
    if params[:code]
      sign_in
    end
  end

  def show
    if @track_id || @like_track_id
      get_track_comments
      embed_soundcloud_widget (@track_id || @like_track_id)
      if @like_track_id
        like @like_track_id
       end
     else
       @aristMusic = @client.get('/tracks', :q => @artist)
     end
  end

  def connect
    redirect_to @client.authorize_url()
  end

  private 

  def get_track_comments
    @track = @client.get('/tracks/' + (@track_id || @like_track_id))
    @comments = Array.new
    @client.get("/tracks/#{@track_id || @like_track_id}/comments").each do |comment|
      @comments.push(comment)
    end
  end

  def like track_id
    @client = Soundcloud.new(:access_token => session[:token]['access_token'])
    @track = @client.get('/tracks/'+track_id)
    @client.put("/me/favorites/#{@track.id}")
  end

  def embed_soundcloud_widget track_id
    track = @client.get('/tracks/' + track_id)
    @embed_info = @client.get('/oembed', :url => track.permalink_url)
    @embedded_track = @embed_info['html'].html_safe
  end

  def get_params
    @artist = params[:id]
    @track_id = params[:comment]
    @like_track_id = params[:track_id]
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
	def soundcloud_connect
		@client ||= Soundcloud.new(:client_id => ENV["CLIENT_ID"],
	                        :client_secret => ENV["CLIENT_SECRET"],
	                        :redirect_uri => ENV["REDIRECT_URL"])
	end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
	
  def sign_in
    code = params[:code]
      if (code && !session[:user])
        @client = Soundcloud.new(:client_id => ENV["CLIENT_ID"],
	                    :client_secret => ENV["CLIENT_SECRET"],
	                    :redirect_uri => ENV["REDIRECT_URL"])
	session[:token] = @client.exchange_token(:code => code)
	access_token = @client.exchange_token(:code => code)
	current_user = @client.get('/me')
        session[:user] = current_user.username
      end
    end

end

app/helpers/track_helper.rb
module TrackHelper 

  def find_url string
    url_array = [] 
    string.scan(/(https?:\/\/([-\w\.]+)+(:\d+)?(\/([\w\/_\.]*(\?\S+)?)?)?)/).each do |url| 
      url_array.push(url[0])
    end
    return url_array
  end

end

app/views/concerts/index.html.erb
<div class="row local-listing-headers" style="margin-top:10%;">
	<!-- headers -->
	<div class="large-6 large-3 columns">
		<p class="local-heading">Artists</p>
	</div>
	<div class="large-1 large-3 columns show-for-large-only">
		<p class="local-heading">Dates</p>
	</div>
	<div class="large-1 large-3 columns show-for-large-only">
		<p class="local-heading">Venues</p>
	</div>

</div>

<div class="row">

	<div class="large-6 large-3 columns">

		<!-- Artist column from cheap thrills' news page -->

		<%= render partial: "shared/local_listings", locals: { column_num: '2', doc: @doc } %>

	</div>

	<div class="large-1 large-3 columns">

		<!-- Date column from cheap thrills' news page  -->

		<%= render partial: "shared/local_listings", locals: { column_num: '3', doc: @doc } %>

	</div>

	<div class="large-1 large-3 columns">

		<!-- Venue column from cheap thrills' news page  -->

		<%= render partial: "shared/local_listings", locals: { column_num: '5', doc: @doc } %>

	</div>

</div>

app/views/concerts/show.html.erb
<div class="headline local-listings-head">  
	<div class="row">
  	<div class="large-12 columns">
  		<div class="row">
  			<div class="large-8 columns">
  				<h1><%= @artist %></h1>
  			</div>
  			<div class="large-4 columns">
  				<%= image_tag("play.png", :class => "poster hide-for-small") %>
  			</div>
  		</div>
    	<div class="row">
    		<% if !@track %>
		      <div class="large-6 columns"> 		
	        	<% if !@aristMusic || !@aristMusic.empty? %>
	        		<p class="lead">Click on the track images for more information and to listen to sample music</p>
	        	<% end %>
      		</div>
      		<div class="large-4 columns">	
        	</div>
        <% end %>
		  </div>
	  </div>
  </div>
</div>
<br/>

<% if !@track %>
  <div class="row">
  <!-- display all tracks that match the @artist keyword if no track_id params provided -->
  <%= render partial: "shared/tracks_list", locals: { artist: @artist, aristMusic: @aristMusic } %>
</div>
  <% else %>
    <!-- if track_id params provided, then display information for the single track -->
  <%= render partial: "shared/single_track", locals: { artist: @artist, track: @track, embedded_track: @embedded_track } %>

    <!-- and also display comments for the single track -->
  <%= render partial: "shared/track_comments", locals: { track: @track, comments: @comments } %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Montreal Concerts</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="contain-to-grid fixed"> 
	<nav class="top-bar montreal">
	  <%= link_to "Montreal Concert Listing", root_path, :class => "main-logo" %>
	  <% unless session[:user] %>
			<%= link_to "Sign in", concerts_authorize_path, :class => "right" %>
		<% end %>
	  <span class="right">Welcome, <%= current_user %></span>
	</nav>
</div>
<div class="row">
<%= yield %>
</div>
</body>
</html>

app/views/shared/_local_listings.html.erb
<% @doc.css('table table tr td:nth-child('+column_num+')').each_with_index do |artist, index| %>
	<% if column_num != '2' %>
		<div class="row show-for-large-only">
	<% else %>
		<div class="row">
	<% end %>
		<div class="large-12 columns">
			<% if column_num == '2' %>
				<%= link_to "#{artist.content}", concert_path(artist.content) if index != 0 %>
			<% else %>
				<span class="dates-venues"> <%= artist.content if index != 0 %></span>
			<% end %>
		</div>
	</div>
<% end %>

app/views/shared/_single_track.html.erb
<!-- display track image or default 'png' if track doesn't have one -->
<div class="row">
	<div class="large-2 columns">
		<%= image_tag(track.artwork_url ? track.artwork_url : "headphones.png", :class => "poster hide-for-small") %>
	</div>
	<div class="large-4 columns panel callout radius">
		<a href="<%= track.permalink_url %>"> <%= track.title %></a>
	</div>

</div>
<!-- embed track -->
<br/>
<%= embedded_track if embedded_track %>
<br/>
<div class="row">
<!-- list favourite count for track, and allow signed-in user to add to favourites -->
Favourite Count: <%= track.favoritings_count %>
<% if session[:user] %>
	<br/>
	<a href="/concerts/<%= artist %>/like/<%= track.id %>">like</a>
<% end %>
<br/><br/>
<!-- display urls from track description -->
<% if track.description %>

	<% find_url(track.description).each do |url| %>
		<a href="<%= url %>"><%= url %></a>
	<% end %>
<% end %>
</div>

app/views/shared/_track_comments.html.erb
<div class="row">
	<% if comments.empty? %>
		<div class="row">
			<div class="medium-2 columns">
				<%= image_tag("sad.png", :class => "poster") %>
			</div>
			<div class="medium-6 columns left">
				<p>There aren't any comments for <i><%= track.title %></i> yet</p>
			</div>
		</div>
	<% else %>

		<br/><%= comments.length %> Comments

		<ul>
			<% comments.each do |comment| %>
				<li>
					<img src="<%= comment.user.avatar_url %>" class="user-avatar"/><br/>
					<strong><%= comment.user.username %></strong> <i>Posted on <%= comment.created_at %></i>
					<blockquote><%= comment.body %></blockquote>
				</li><br/>
			<% end %>
		</ul>

	<% end %>
</div>

app/views/shared/_tracks_list.html.erb
<% if aristMusic.empty? %>
  <div class="row">
    <div class='medium-2 columns'>
      <%= image_tag("sad.png", :class => "poster") %>
    </div>
    <div class='medium-6 columns left'>
      <p>Sorry, we don't have any sample music matching <%= artist %> at this time</p>
    </div>
 </div>

<% else %>

  <% aristMusic.in_groups_of(4, false).each do |group| %>
    <div class="row tracks-list-grid">
      <% group.each do |track| %>
        <div class='large-3 columns'>
          <a href="/concerts/<%= @artist %>/comments/<%= track.id %>"><%= image_tag(track.artwork_url ? track.artwork_url : "headphones.png", :class => "poster track-listing-poster") %></a>
	  <br/>
          <div class="row">
	    <div class='large-6 columns title-description'>
	      <a data-tooltip aria-haspopup="true" title="<%= track.description %>" class="track-listing-title has-tip" href="<%= track.permalink_url %>"> <%= truncate(track.title, :length => 50) %> </a>
	    </div>
	  </div>
        </div>
    <% end %>
  </div>
<% end %>

<% end %>